# Site settings
title: Veyon – Cross-platform computer monitoring and classroom management
email: info@veyon.io
description: >
  This is the official website of the Veyon project (Virtual Eye On Networks) ran by the Veyon community. The website contains a download area, documentation and a blog.
baseurl: ""
url: "https://veyon.io"

gems:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 5
paginate_path: "/blog/page:num/"

permalink: /blog/:year/:month/:day/:title/

# Build settings
markdown: kramdown
exclude:
  - README.md
